# Generated by Django 4.1.9 on 2023-12-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trip',
            field=models.CharField(default='', max_length=255),
        ),
    ]
