# Generated by Django 4.1.9 on 2023-12-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='caption',
        ),
    ]
