# Generated by Django 4.1.9 on 2023-12-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.TextField(blank=True),
        ),
    ]
